### ISSUE TITLE
Distinct Id in Mixpanel is displayed as `auth0_logs`

### ISSUE THREAD

**Issue by jerzzhang** [auth0/auth0-logs-to-mixpanel#11]
Currently, when I import the logs into Mixpanel the DistinctId is shown as `auth0_logs`. I think it would be more useful to have the `distinct_id` to be the `user_id`. It seems like in the line below the `distinct_id` is set but not propagated into Mixpanel.

https://github.com/auth0/auth0-logs-to-mixpanel/blob/1f2f00b1f3b4c6fc437c4bf79e631eadb3c717af/server/lib/processLogs.js#L67

**Comment by austince** [comment]
I have been seeing the `distinct_id` set to just the `user_id` without the `provider` prefix, which is also not useful. Trying to get a PR together to provide that as a configuration but having difficulty running this locally. Seems there are many conflicts with the node versions / dependencies. Anyone from auth0 team have a guide to get this running locally? @jcenturion @arcseldon @zxan1285?

**Comment by austince** [comment]
@jerzzhang this is how the `distinct_id` is currently set: 
https://github.com/auth0-extensions/auth0-logs-to-mixpanel/blob/38efe598ec28b79c3b88e629e18e0ffbdd23d236/server/lib/processLogs.js#L67

Not sure which place that value could be coming from.

**Comment by fyockm** [comment]
@austince thanks for moving to https://github.com/auth0-extensions/auth0-logs-to-provider/issues/7
closing issue here in favor of that one.
